---
version: "3.7"
services:
  sc4s:
    image: docker.io/splunk/scs:latest
    ports:  
       - target: 514
         published: 514
         protocol: tcp
       - target: 514
         published: 514
         protocol: udp
       #- target: 601
       #  published: 601
       #  protocol: tcp
       #- target: 6514
       #  published: 6514
       #  protocol: tcp
    env_file:
      - env_file
    volumes:
      - /opt/sc4s/local:/etc/syslog-ng/conf.d/local:z
      - splunk-sc4s-var:/var/lib/syslog-ng
# Uncomment the following line if local disk archiving is desired
#     - /opt/sc4s/archive:/var/lib/syslog-ng/archive:z
# Uncomment the following line if custom TLS certs are provided
#     - /opt/sc4s/tls:/etc/syslog-ng/tls:z

volumes:
  splunk-sc4s-var: